# Non Graded Challange 11

- Name  : Cici Yuriza
- Batch : HCK-005

#### Load Data

In [254]:
# import Library
import pandas as pd
import numpy as np

In [255]:
# Loading data
df = pd.read_csv('Dataset/covid_19_indonesia_time_series_all.csv')

In [256]:
# tampilkan all columns in dataframe
pd.set_option("display.max.columns", None)

In [257]:
df.head()

Date Location ISO Code     Location  New Cases  New Deaths  \
0  3/1/2020             ID-JK  DKI Jakarta          2           0   
1  3/2/2020             ID-JK  DKI Jakarta          2           0   
2  3/2/2020               IDN    Indonesia          2           0   
3  3/2/2020             ID-RI         Riau          1           0   
4  3/3/2020             ID-JK  DKI Jakarta          2           0   

   New Recovered  New Active Cases  Total Cases  Total Deaths  \
0              0                 2           39            20   
1              0                 2           41            20   
2              0                 2            2             0   
3              0                 1            1             0   
4              0                 2           43            20   

   Total Recovered  Total Active Cases Location Level  City or Regency  \
0               75                 -56       Province              NaN   
1               75                 -54       Province              NaN   
2                0                   2        Country              NaN   
3                1                   0       Province              NaN   
4               75                 -52       Province              NaN   

      Province    Country Continent    Island  Time Zone  \
0  DKI Jakarta  Indonesia      Asia      Jawa  UTC+07:00   
1  DKI Jakarta  Indonesia      Asia      Jawa  UTC+07:00   
2          NaN  Indonesia      Asia       NaN        NaN   
3         Riau  Indonesia      Asia  Sumatera  UTC+07:00   
4  DKI Jakarta  Indonesia      Asia      Jawa  UTC+07:00   

           Special Status  Total Regencies  Total Cities  Total Districts  \
0  Daerah Khusus Ibu Kota                1           5.0               44   
1  Daerah Khusus Ibu Kota                1           5.0               44   
2                     NaN              416          98.0             7230   
3                     NaN               10           2.0              169   
4  Daerah Khusus Ibu Kota                1           5.0               44   

   Total Urban Villages  Total Rural Villages  Area (km2)  Population  \
0                 267.0                   NaN         664    10846145   
1                 267.0                   NaN         664    10846145   
2                8488.0               74953.0     1916907   265185520   
3                 268.0                1591.0       87024     6074100   
4                 267.0                   NaN         664    10846145   

   Population Density   Longitude  Latitude  New Cases per Million  \
0            16334.31  106.836118 -6.204699                   0.18   
1            16334.31  106.836118 -6.204699                   0.18   
2              138.34  113.921327 -0.789275                   0.01   
3               69.80  101.805109  0.511648                   0.16   
4            16334.31  106.836118 -6.204699                   0.18   

   Total Cases per Million  New Deaths per Million  Total Deaths per Million  \
0                     3.60                     0.0                      1.84   
1                     3.78                     0.0                      1.84   
2                     0.01                     0.0                      0.00   
3                     0.16                     0.0                      0.00   
4                     3.96                     0.0                      1.84   

   Total Deaths per 100rb Case Fatality Rate Case Recovered Rate  \
0                    0.18             51.28%             192.31%   
1                    0.18             48.78%             182.93%   
2                    0.00              0.00%               0.00%   
3                    0.00              0.00%             100.00%   
4                    0.18             46.51%             174.42%   

   Growth Factor of New Cases  Growth Factor of New Deaths  
0                         NaN                          NaN  
1                         1.0                          1.0  

In [258]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31822 entries, 0 to 31821
Data columns (total 38 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   Date                         31822 non-null  object 
 1   Location ISO Code            31822 non-null  object 
 2   Location                     31822 non-null  object 
 3   New Cases                    31822 non-null  int64  
 4   New Deaths                   31822 non-null  int64  
 5   New Recovered                31822 non-null  int64  
 6   New Active Cases             31822 non-null  int64  
 7   Total Cases                  31822 non-null  int64  
 8   Total Deaths                 31822 non-null  int64  
 9   Total Recovered              31822 non-null  int64  
 10  Total Active Cases           31822 non-null  int64  
 11  Location Level               31822 non-null  object 
 12  City or Regency              0 non-null      float64
 13  Province        

In [259]:
# change type data Date from object to datetime
df['Date'] = pd.to_datetime(df['Date'])

In [260]:
# Membuat dataframe baru
df_new = df[['Date',
                'Location',
                'New Cases',
                'New Deaths',
                'New Recovered',
                'New Active Cases',
                'Total Cases',
                'Total Deaths',
                'Total Recovered',
                'Total Active Cases'
                ]].query(("Location == 'DKI Jakarta' & Date.dt.year > 2021"))
# drop location column
df_new.drop(columns='Location',inplace=True)

df_new.head()

Date  New Cases  New Deaths  New Recovered  New Active Cases  \
22797 2022-01-01        118           0             46                72   
22832 2022-01-02        103           0            106                -3   
22867 2022-01-03        172           0             23               149   
22902 2022-01-04        115           0             42                73   
22937 2022-01-05        260           0             71               189   

       Total Cases  Total Deaths  Total Recovered  Total Active Cases  
22797       865415         13609           851282                 524  
22832       865518         13609           851388                 521  
22867       865690         13609           851411                 670  
22902       865805         13609           851453                 743  
22937       866065         13609           851524                 932

In [261]:
# reset index from 0
df_new = df_new[df_new["Date"] != None ].reset_index(drop=True)

In [262]:
df_new.head()

Date  New Cases  New Deaths  New Recovered  New Active Cases  \
0 2022-01-01        118           0             46                72   
1 2022-01-02        103           0            106                -3   
2 2022-01-03        172           0             23               149   
3 2022-01-04        115           0             42                73   
4 2022-01-05        260           0             71               189   

   Total Cases  Total Deaths  Total Recovered  Total Active Cases  
0       865415         13609           851282                 524  
1       865518         13609           851388                 521  
2       865690         13609           851411                 670  
3       865805         13609           851453                 743  
4       866065         13609           851524                 932

### Lakukan hypothesis testing terhadap dataset covid 19

In [263]:
df_month_1_to_4  = df_new[df_new['Date'].dt.month <= 4][['Date','New Cases']]
df_month_5_to_9 = df_new[df_new['Date'].dt.month > 4][['Date','New Cases']]


print('Average New Cases a day in month 1 to 4 2022 is {}'.format(np.round(df_month_1_to_4['New Cases'].mean())))
print('Average New Cases a day in month 5 to 9 2022 is {}'.format(np.round(df_month_5_to_9['New Cases'].mean())))

Average New Cases a day in month 1 to 4 2022 is 3187.0
Average New Cases a day in month 5 to 9 2022 is 1194.0


In [264]:
# set date to be index
df_month_1_to_4.set_index('Date',inplace=True)
df_month_5_to_9.set_index('Date',inplace=True)

mean1 = Average New Cases a day in month 1 to 4 2022 is 3187.0\
mean2 = Average New Cases a day in month 5 to 9 2022 is 1194.0

**Hypothesis :\
H0 : mean1 >= mean2\
H1 : mean1 < mean2**

Analisis menggunakan two sample independent two tailed

In [265]:
from scipy import stats
t_stat, p_val = stats.ttest_ind(df_month_1_to_4,df_month_5_to_9)
print('P-value:',p_val[0]/2) #the p-value isn't divided by 2 since the output is two-sided p-value
print('t-statistics:',t_stat[0])

P-value: 1.2230945500014422e-08
t-statistics: 5.756733893971875


alpha = 0.05\
p-value = 0.000000012230945500014422\
p-value < alpha\
`H0 rejected`

### Kesimpulan dari hasil analisa.


Dari testing hipotesis diatas **H0 rejected**, kesimpulan yang dapat diambil adalah bahwa, kasus baru covid-19 di DKI Jakarta `per hari` pada januari, februari, maret dan april ***tidak signifikan lebih banyak*** dari mei, juni, juli, agustus dan september tahun 2022.